version: 2

sources:
  - name: raw_github
    description: "Raw GitHub data stored in MotherDuck raw schema"
    database: mds_health_db
    schema: raw
    tables:
      - name: dbt_core_issues
        description: "Raw GitHub issues for dbt-core"
      
      - name: dbt_core_pulls
        description: "Raw GitHub pull requests for dbt-core"
      
      - name: dbt_core_releases
        description: "Raw GitHub releases for dbt-core"