version: 2

sources:
  - name: raw_github
    description: "Raw GitHub data"
    schema: raw
    freshness:
      warn_after: {count: 2, period: day}
      error_after: {count: 3, period: day}
    loaded_at_field: updated_at
    tables:
      # dbt-core
      - name: dbt_core_issues
        description: "Raw GitHub issues for dbt-core"
      - name: dbt_core_pulls
        description: "Raw GitHub pull requests for dbt-core"
      - name: dbt_core_releases
        description: "Raw GitHub releases for dbt-core"
        freshness:
          warn_after: {count: 30, period: day}
          error_after: {count: 60, period: day}
      
      # Apache Airflow
      - name: airflow_issues
        description: "Raw GitHub issues for Apache Airflow"
      - name: airflow_pulls
        description: "Raw GitHub pull requests for Apache Airflow"
      - name: airflow_releases
        description: "Raw GitHub releases for Apache Airflow"
        freshness:
          warn_after: {count: 30, period: day}
          error_after: {count: 60, period: day}
      
      # Dagster
      - name: dagster_issues
        description: "Raw GitHub issues for Dagster"
      - name: dagster_pulls
        description: "Raw GitHub pull requests for Dagster"
      - name: dagster_releases
        description: "Raw GitHub releases for Dagster"
        freshness:
          warn_after: {count: 30, period: day}
          error_after: {count: 60, period: day}      